server:
  port: 8010

spring:
  application:
    name: "accounts"
  config:
    import:
      - "application_prod.yml"
      - "application_qa.yml"
  profiles:
    active:
      - "qa"
support:
  message : "Bienvenidos al sistema bancario de accenture"
  contactInfo:
    name: "Sebastián Hoyos"
    email: "sebashoyos5163@gmail.com"
  phoneNumbers:
    - (57) 3003003003030
    - (57) 3003003003030
